apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend
  namespace: bake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-backend
  template:
    metadata:
      labels:
        app: web-backend
    spec:
      containers:
      - name: web-backend
        image: saassvctstacr.azurecr.io/bake:dev
        securityContext:
          runAsUser: 33
          runAsGroup: 33
        ports:
          - containerPort: 8000
        imagePullPolicy: Always # forces image repull on scale
        envFrom:
          - configMapRef:
             name: web-config
        volumeMounts:
        - mountPath: "/media"
          name: media 
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: akc-bake-files 
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - web-backend
              topologyKey: "kubernetes.io/hostname"

