apiVersion: v1
kind: Service
metadata:
  name: web-backend
  namespace: bake
spec:
  type: NodePort
  selector:
    app: web-backend
  ports:
  - name: pgadmin-port
    port: 80
    targetPort: 8000

