apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akc-bake-files 
  namespace: bake
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 32Gi 

