apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: bake
spec:
  selector:
    matchLabels:
      pod: redis
  replicas: 1
  template:
    metadata:
      labels:
        pod: redis
    spec:
      containers:
        - name: master
          image: redis:7.2.5-bookworm
          env:
            - name: REDIS_PASSWORD
              value: 
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
